---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: sealed-secrets
      version: 2.17.3
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: flux-system
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    image:
      repository: bitnamilegacy/sealed-secrets-controller
    rbac:
      create: true
      pspEnabled: false
    podSecurityContext:
      enabled: true
      fsGroup: 65534
    containerSecurityContext:
      enabled: true
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1001
      seccompProfile:
        type: RuntimeDefault
      capabilities: {}
        # drop:
        #   - ALL
    resources:
      requests:
        cpu: 50m
        memory: 50Mi
